module.exports = {
  siteTitle: 'JJUG CCC 2022 Spring',
  siteTitleAlt: 'JJUG CCC',
  siteLogo: '/icons/logo_512.png',
  siteUrl: 'https://ccc2022spring.java-users.jp/',
  pathPrefix: '',
  siteDescription: 'JJUG CCC 2022 Spring/Japan Java User Group Cross Community Conference 2022 Spring',
  siteRss: '/rss.xml',
  siteFBAppID: '',
  googleTagManagerID: '',
  disqusShortname: 'jjug-ccc-2022-spring',
  userName: 'JJUG',
  userTwitter: 'JJUG',
  userLocation: 'Tokyo',
  userDescription: 'Japan Java User Group',
  copyright: 'Copyright © 2007-2022 JJUG - All rights reserved.',
  themeColor: '#76A80A9E',
  backgroundColor: '#ffffff',
}
